apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lldap-chart.fullname" . }}-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: lldap
    {{- include "lldap-chart.labels" . | nindent 4 }}
  annotations:
    lldap: https://github.com/nitnelave/lldap
    k8s: https://github.com/michael2to3/lldap-kubernetes
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: lldap
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lldap
        {{- include "lldap-chart.selectorLabels" . | nindent 8 }}
      annotations:
        lldap: https://github.com/nitnelave/lldap
        k8s: https://github.com/michael2to3/lldap-kubernetes
    spec:
      containers:
        - name: lldap
          image: "{{ .Values.image.repository }}:{{ include "lldap-chart.imageTag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}

          env:
            - name: GID
              value: "{{ .Values.env.GID }}"
            - name: TZ
              value: "{{ .Values.env.TZ }}"
            - name: UID
              value: "{{ .Values.env.UID }}"

          {{- if .Values.extraEnv }}
          {{ toYaml .Values.extraEnv | nindent 12 }}
          {{- end }}

          {{- if .Values.envFrom }}
          envFrom:
          {{ toYaml .Values.envFrom | nindent 12 }}
          {{- end }}

          ports:
            - containerPort: 3890
            - containerPort: 6360
            - containerPort: 17170
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - mountPath: /data
              name: lldap-data
            {{- end }}

            {{- if .Values.extraVolumeMounts}}
            {{- toYaml .Values.extraVolumeMounts | nindent 12}}
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled}}
        - name: lldap-data
          persistentVolumeClaim:
            claimName: {{ include "lldap-chart.fullname" . }}-data
        {{- end }}

        {{- if .Values.extraVolumes}}
        {{- toYaml .Values.extraVolumes | nindent 8}}
        {{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
